version: '3.8'

services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://root:password@host.docker.internal:5433/aliases_service
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: root
      PGRST_SERVER_PORT: 3000
    networks:
      - pgeonui-network
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      API_URL: http://localhost:3000/

networks:
  pgeonui-network:
    driver: bridge