version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - pgeonui-network
    volumes:
      - test-db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://root:password@postgres:5432/test-db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: root
      PGRST_SERVER_PORT: 3000
    networks:
      - pgeonui-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      API_URL: http://localhost:3000/

networks:
  pgeonui-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  test-db-data:
    driver: local
