# Global config
global:
  scrape_interval: 10s
  evaluation_interval: 10s

# Scrape configurations
scrape_configs:
  - job_name: 'pgeonui'
    static_configs:
      - targets: ['pgeonui:8082']
    metrics_path: '/q/metrics'