name: Build and Push Image

on:
  push:
    branches:
      - main
      - test-ci

jobs:
  build-native-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get project version from Gradle
        id: get_version
        run: |
          PROJECT_VERSION=$(./gradlew properties --no-daemon | grep "^version:" | awk '{print $2}')
          echo "version=$PROJECT_VERSION" >> "$GITHUB_OUTPUT"
          echo "Detected project version: $PROJECT_VERSION"

      - name: Build native image and container
        run: |
          ./gradlew build \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.image=docker.io/bdnk/pgeonui \
            -Dquarkus.container-image.additional-tags=${{ steps.get_version.outputs.version }} 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bdnk
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker images (Version and Latest)
        run: |
          BASE_IMAGE="docker.io/bdnk/pgeonui"
          GRADLE_VERSION_TAG=${{ steps.get_version.outputs.version }}
          
          echo "Pushing tags for $BASE_IMAGE: $GRADLE_VERSION_TAG and latest"

          docker push $BASE_IMAGE:$GRADLE_VERSION_TAG

          docker push $BASE_IMAGE:latest
